### ISSUE TITLE
How about non-panicking?

### ISSUE THREAD

**Issue by e-oz** [sacooper/xmlJSON-rs#3]
Please consider to replace `panic`s to returning Err<String>. Invalid XML is not always too critical error to kill everybody else in the room.

**Comment by sacooper** [comment]
Apologies for the late reply. This is definitely on my ToDo list. In the next week or two, I'm hoping to publish v0.2.0 which will encompass a few bug fixes, as well as improved errors.

**Comment by sacooper** [comment]
Sorry about the delay, but version 0.2.0 has been published, and this has been fixed. If there's any other issues/features you'd like, let me know!

**Comment by e-oz** [comment]
Thank you!
